version: '0'
services:
  lanzadorServicios:
    image: ignacioibanez/ml-modeling
    environment:
      entradas: ${ENTRADAS}
      access_key: ${ACCESS_KEY}
      secret_key: ${SECRET_KEY}
      url: ${URL}
      url_catalog: ${URL_CATALOG}
    stdin_open: true
    entrypoint:
      - 
      - python lanzadorServicios.py $$entradas $$access-key $$secret-key $$url $$url_catalog
    tty: true
