version: '0'
services:
  lanzadorServicios:
    image: ignacioibanez/ml-modeling
    environment:
      access_key: ${ACCESS_KEY}
      secret_key: ${SECRET_KEY}
      url: ${URL}
      url_catalog: ${URL_CATALOG}
      url_entradas: ${URL_ENTRADAS}
    stdin_open: true
    entrypoint:
      - python lanzadorServicios.py $$url_entradas $$access-key $$secret-key $$url $$url_catalog
    tty: true
